name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build for multiple platforms
        run: |
          GOOS=darwin GOARCH=amd64 go build -o ask-darwin-amd64 main.go
          GOOS=darwin GOARCH=arm64 go build -o ask-darwin-arm64 main.go
          GOOS=linux GOARCH=amd64 go build -o ask-linux-amd64 main.go
          GOOS=linux GOARCH=arm64 go build -o ask-linux-arm64 main.go

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ask-darwin-amd64
            ask-darwin-arm64
            ask-linux-amd64
            ask-linux-arm64
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 